services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - my-network

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - my-network

volumes:
  redis-data:
    driver: local

networks:
  my-network:
    driver: bridge